v2_header = [
    'GLOBALEVENTID',
    'SQLDATE',
    'MonthYear',
    'Year',
    'FractionDate',
    'Actor1Code',
    'Actor1Name',
    'Actor1CountryCode',
    'Actor1KnownGroupCode',
    'Actor1EthnicCode',
    'Actor1Religion1Code',
    'Actor1Religion2Code',
    'Actor1Type1Code',
    'Actor1Type2Code',
    'Actor1Type3Code',
    'Actor2Code',
    'Actor2Name',
    'Actor2CountryCode',
    'Actor2KnownGroupCode',
    'Actor2EthnicCode',
    'Actor2Religion1Code',
    'Actor2Religion2Code',
    'Actor2Type1Code',
    'Actor2Type2Code',
    'Actor2Type3Code',
    'IsRootEvent',
    'EventCode',
    'EventBaseCode',
    'EventRootCode',
    'QuadClass',
    'GoldsteinScale',
    'NumMentions',
    'NumSources',
    'NumArticles',
    'AvgTone',
    'Actor1Geo_Type',
    'Actor1Geo_FullName',
    'Actor1Geo_CountryCode',
    'Actor1Geo_ADM1Code',
    'Actor1Geo_ADM2Code',
    'Actor1Geo_Lat',
    'Actor1Geo_Long',
    'Actor1Geo_FeatureID',
    'Actor2Geo_Type',
    'Actor2Geo_FullName',
    'Actor2Geo_CountryCode',
    'Actor2Geo_ADM1Code',
    'Actor2Geo_ADM2Code',
    'Actor2Geo_Lat',
    'Actor2Geo_Long',
    'Actor2Geo_FeatureID',
    'ActionGeo_Type',
    'ActionGeo_FullName',
    'ActionGeo_CountryCode',
    'ActionGeo_ADM1Code',
    'ActionGeo_ADM2Code',
    'ActionGeo_Lat',
    'ActionGeo_Long',
    'ActionGeo_FeatureID',
    'DATEADDED',
    'SOURCEURL'
]

v1_header = [
    'GLOBALEVENTID',
    'SQLDATE',
    'MonthYear',
    'Year',
    'FractionDate',
    'Actor1Code',
    'Actor1Name',
    'Actor1CountryCode',
    'Actor1KnownGroupCode',
    'Actor1EthnicCode',
    'Actor1Religion1Code',
    'Actor1Religion2Code',
    'Actor1Type1Code',
    'Actor1Type2Code',
    'Actor1Type3Code',
    'Actor2Code',
    'Actor2Name',
    'Actor2CountryCode',
    'Actor2KnownGroupCode',
    'Actor2EthnicCode',
    'Actor2Religion1Code',
    'Actor2Religion2Code',
    'Actor2Type1Code',
    'Actor2Type2Code',
    'Actor2Type3Code',
    'IsRootEvent',
    'EventCode',
    'EventBaseCode',
    'EventRootCode',
    'QuadClass',
    'GoldsteinScale',
    'NumMentions',
    'NumSources',
    'NumArticles',
    'AvgTone',
    'Actor1Geo_Type',
    'Actor1Geo_FullName',
    'Actor1Geo_CountryCode',
    'Actor1Geo_ADM1Code',
    'Actor1Geo_Lat',
    'Actor1Geo_Long',
    'Actor1Geo_FeatureID',
    'Actor2Geo_Type',
    'Actor2Geo_FullName',
    'Actor2Geo_CountryCode',
    'Actor2Geo_ADM1Code',
    'Actor2Geo_Lat',
    'Actor2Geo_Long',
    'Actor2Geo_FeatureID',
    'ActionGeo_Type',
    'ActionGeo_FullName',
    'ActionGeo_CountryCode',
    'ActionGeo_ADM1Code',
    'ActionGeo_Lat',
    'ActionGeo_Long',
    'ActionGeo_FeatureID',
    'DATEADDED',
    'SOURCEURL'
]

article_columns = [
    'GLOBALEVENTID',
    'TITLE',
    'SITE',
    'SUMMARY',
    'KEYWORDS',
    'META'
]

cameo = {
    '1':  'Public Comment',
    '2':  'Appeal',
    '3':  'Cooperate',
    '4':  'Consult',
    '5':  'Diplomatic',
    '6':  'Material',
    '7':  'Aid',
    '8':  'Yield',
    '9':  'Investigate',
    '10': 'Demand',
    '11': 'Disapprove',
    '12': 'Reject',
    '13': 'Threaten',
    '14': 'Protest',
    '15': 'Force Posture',
    '16': 'Reduce Relations',
    '17': 'Coerce',
    '18': 'Assault',
    '19': 'Fight',
    '20': 'Mass Violence'
}

dtype_map = {
    'isrootevent': str,
    'eventcode': str,
    'eventbasecode': str,
    'eventrootcode': str,
    'globaleventid': str,
    'dateadded': str,
    'sqldate': int,
    'monthyear': int,
    'year': int,
    'fractiondate': float,
    'actiongeo type': int,
    'actor1code': str,
    'actor2code': str,
    'actor1name': str,
    'actor2name': str,
    'actor1countrycode': str,
    'actor2countrycode': str,
    'actor1knowngroupcode': str,
    'actor2knowngroupcode': str,
    'actor1ethniccode': str,
    'actor2ethniccode': str,
    'actor1religion1code': str,
    'actor2religion1code': str,
    'actor1religion2code': str,
    'actor2religion2code': str,
    'actor1type1code': str,
    'actor2type1code': str,
    'actor1type2code': str,
    'actor2type2code': str,
    'actor1type3code': str,
    'actor2type3code': str,
    'quadclass': str,
    'goldsteinscale': float,
    'nummentions': int,
    'numsources': int,
    'numarticles': int,
    'avgtone': float,
    'actiongeo_fullname': str,
    'actiongeo_lat': float,
    'actiongeo_long': float,
    'actiongeo_featureid': str,
    'actor1geo_fullname': str,
    'actor1geo_countrycode': str,
    'actor1geo_adm1code': str,
    'actor1geo_lat': float,
    'actor1geo_long': float,
    'actor1geo_featureid': str,
    'actor2geo_fullname': str,
    'actor2geo_countrycode': str,
    'actor2geo_adm1code': str,
    'actor2geo_lat': float,
    'actor2geo_long': float,
    'actor2geo_featureid': str
}
